#ifndef QTQMLANDROIDGRAVITY_P_H
#define QTQMLANDROIDGRAVITY_P_H

#include <QtCore/qobject.h>

QT_BEGIN_NAMESPACE

class QQmlAndroidGravity : public QObject
{
    Q_OBJECT
    Q_FLAGS(Flags)

public:
    enum Flag {
        NO_GRAVITY = 0x0000,
        AXIS_SPECIFIED = 0x0001,
        AXIS_PULL_BEFORE = 0x0002,
        AXIS_PULL_AFTER = 0x0004,
        AXIS_CLIP = 0x0008,
        AXIS_X_SHIFT = 0,
        AXIS_Y_SHIFT = 4,
        TOP = (AXIS_PULL_BEFORE|AXIS_SPECIFIED)<<AXIS_Y_SHIFT,
        BOTTOM = (AXIS_PULL_AFTER|AXIS_SPECIFIED)<<AXIS_Y_SHIFT,
        LEFT = (AXIS_PULL_BEFORE|AXIS_SPECIFIED)<<AXIS_X_SHIFT,
        RIGHT = (AXIS_PULL_AFTER|AXIS_SPECIFIED)<<AXIS_X_SHIFT,
        CENTER_VERTICAL = AXIS_SPECIFIED<<AXIS_Y_SHIFT,
        FILL_VERTICAL = TOP|BOTTOM,
        CENTER_HORIZONTAL = AXIS_SPECIFIED<<AXIS_X_SHIFT,
        FILL_HORIZONTAL = LEFT|RIGHT,
        CENTER = CENTER_VERTICAL|CENTER_HORIZONTAL,
        FILL = FILL_VERTICAL|FILL_HORIZONTAL,
        CLIP_VERTICAL = AXIS_CLIP<<AXIS_Y_SHIFT,
        CLIP_HORIZONTAL = AXIS_CLIP<<AXIS_X_SHIFT,
        RELATIVE_LAYOUT_DIRECTION = 0x00800000,
        HORIZONTAL_GRAVITY_MASK = (AXIS_SPECIFIED |
                AXIS_PULL_BEFORE | AXIS_PULL_AFTER) << AXIS_X_SHIFT,
        VERTICAL_GRAVITY_MASK = (AXIS_SPECIFIED |
                AXIS_PULL_BEFORE | AXIS_PULL_AFTER) << AXIS_Y_SHIFT,
        DISPLAY_CLIP_VERTICAL = 0x10000000,
        DISPLAY_CLIP_HORIZONTAL = 0x01000000,
        START = RELATIVE_LAYOUT_DIRECTION | LEFT,
        END = RELATIVE_LAYOUT_DIRECTION | RIGHT,
        RELATIVE_HORIZONTAL_GRAVITY_MASK = START | END
    };
    Q_DECLARE_FLAGS(Flags, Flag)
};

Q_DECLARE_OPERATORS_FOR_FLAGS(QQmlAndroidGravity::Flags)

QT_END_NAMESPACE

#endif // QTQMLANDROIDGRAVITY_P_H
