include(app/app.pri)
include(core/core.pri)
include(content/content.pri)
include(graphics/graphics.pri)
include(java/java.pri)
include(support/support.pri)
include(view/view.pri)
include(widget/widget.pri)
